language: nix
script: nix-build --expr "with import <nixpkgs> {}; pkgs.callPackage ./default.nix {}"
deploy:
  provider: releases
  api_key:
    secure: ObPXZmge1XtyOcEWbtHgtRvUoz+nACRDTENY4e72XGlRNqQjJhFTddKcHxST4xy/duYMDR0M4RW6XlprRbPR7pGvS/+1ktH78LMQrqG0Q/lXU5p8GmjjaPwLDGCgUTndFfgBqR94xMxWJxJaZWJ4fDM7L8YClWlDBEbkTt9QXvQLJiDQwJ/FjJs6owfekPMskIHyCJ2LawTdzUrUWmpLTsJESR1A0Upt4cL7111gaZaUmh5cPXy8nRrFdjS6PTrep+r4Nu2vhu8ukHgMnjeWEVcOcvjcKuSrRAD3kWOyLzS/CCQzRQEH1ZGsy1ysfUaKTRqpoSC7iINdkNgeN1KyZXv+jMw7VpSJZB+I+HI8dreUBMdG5M+SPrdrsSwdleKhEEK5hPiJASDPTJFCbn5aTJeuupUPG9AgSUM+4i7/4s+I4LMbnuTIu6dWOqlmtq6QBUPw6dJl5HfcOyzEC6i9wJbdbukI8Dt8hXtUQjvogqPOPaMsBNHI9AA5AIY792trTQFMPlvnIdySL3ctfTBJ0WdO5+Sj95yzDBz1rnZbsjfHqsklaKzlHrIw3N1CulmA/XAgN+haAUHyUR8X0YMXsED4iHQHMrh5J7Xi6O9Cshc6Iy7FirsaBIFWNGjKr+qK2g92/sfmL8hqX2Ud155En5Iko/H+pRhRjcwaop4y9/Q=
  file: result/table.pdf
  skip_cleanup: true
  on:
    tags: true
